### ISSUE TITLE
Please, update mode for the newer version of the game!

### ISSUE THREAD

**Issue by trikstir** [armedturret/PrimePresidents#3]
Hi there! I came back to the game with the new update and accidentally discovered that this mode is not working on this version. This mod was too funny can't imagine a game without it xd...

**Comment by kierkat10** [comment]
yep

**Comment by armedturret** [comment]
Hi, it si fix please check moddb

**Comment by kierkat10** [comment]
...moddb? If you mean thunderstore, it is still not updated :P

And if you don't mean thunderstore, can you please provide the link for the mod?
